### ISSUE TITLE
青空文庫形式のファイルの所在

### ISSUE THREAD

**Issue by hokorobi** [gennei/aozora_todo#3]
作品の html, zip などは Web サーバにあると思いますが、青空文庫形式のファイルはなさそうでした。
校正サーバ内だけにあるということはありませんか？

**Comment by takahashim** [comment]
zipを展開すれば青空文庫形式のファイルになるはずです

**Comment by hokorobi** [comment]
なるほど。
校正サーバに青空文庫形式のテキストファイルがあって、校正サーバ内でそれを圧縮、html 化ほかして Web サーバに配布するという形ですかね。
